/**
 * OpeniBank Educator — shared types.
 *
 * The curriculum is authored as plain TypeScript data (see
 * `content/worlds.ts`). These types describe the shape of every lesson,
 * exercise, badge, and progress record.
 *
 * The design is compliance-safe by construction:
 *   - every Lesson carries a `safetyTakeaway`
 *   - exercises only test understanding, never simulate real money
 *   - the AI tutor adapter takes a lesson context, never a portfolio
 */

// ── Curriculum structure ────────────────────────────────────────────────

export type WorldId =
  | 'w1-digital-money'
  | 'w2-wallet-basics'
  | 'w3-wallet-security'
  | 'w4-transactions'
  | 'w5-token-literacy'
  | 'w6-risk-control'
  | 'w7-defi-safety'
  | 'w8-advanced-ops'
  | 'w9-openibank-mastery'

export interface World {
  id: WorldId
  index: number
  title: string
  tagline: string
  glyph: string           // short emoji/icon tag rendered by Character/LevelMap
  accent: string          // hex color for theme accent
  levels: Level[]
}

export interface Level {
  id: string              // `${worldId}.l${n}`
  index: number
  title: string
  summary: string
  lessons: Lesson[]
}

export interface Lesson {
  id: string              // `${levelId}.lesson${n}`
  title: string
  /** ~1 sentence scenario/question that hooks the learner. */
  hook: string
  /** Short explanation paragraphs (plain prose, 2–4 sentences each). */
  explain: string[]
  /** One or two interactive exercises. */
  exercises: Exercise[]
  /** Authored one-line operational rule. Never generated by AI. */
  safetyTakeaway: string
  /** Tags for spaced-review bucketing and tutor retrieval. */
  reviewTags: string[]
  /** XP awarded on first completion. */
  xp: number
}

export type Exercise =
  | MultipleChoiceExercise
  | TrueFalseExercise
  | OrderingExercise
  | ScenarioExercise

interface ExerciseBase {
  id: string
  prompt: string
  explain?: string        // shown after answer regardless of correctness
}

export interface MultipleChoiceExercise extends ExerciseBase {
  kind: 'mcq'
  choices: Array<{ id: string; label: string; correct?: boolean }>
}

export interface TrueFalseExercise extends ExerciseBase {
  kind: 'tf'
  answer: boolean
}

/** User must drag steps into the correct order. */
export interface OrderingExercise extends ExerciseBase {
  kind: 'order'
  steps: string[]        // authored in the CORRECT order; UI shuffles on render
}

/** Branching scenario — also used by PracticeTab for drills. */
export interface ScenarioExercise extends ExerciseBase {
  kind: 'scenario'
  context: string
  choices: Array<{
    id: string
    label: string
    outcome: 'safe' | 'risky' | 'catastrophic'
    explain: string
  }>
  correctChoiceId: string
}

// ── Practice scenarios ──────────────────────────────────────────────────

export type ScenarioTopic =
  | 'phishing'
  | 'approval'
  | 'network-mismatch'
  | 'seed-phrase'
  | 'fake-support'
  | 'fake-airdrop'

export interface Scenario {
  id: string
  topic: ScenarioTopic
  title: string
  summary: string
  exercise: ScenarioExercise
  /** Where to send the user for reinforcement. */
  reinforceLesson?: string
}

// ── Badges ──────────────────────────────────────────────────────────────

export type BadgeId =
  | 'seed-phrase-guardian'
  | 'scam-spotter'
  | 'safe-signer'
  | 'gas-explorer'
  | 'wallet-builder'
  | 'defi-cautious-explorer'
  | 'ibank-wallet-ready'

export interface Badge {
  id: BadgeId
  label: string
  description: string
  glyph: string
  /** Earned when this predicate is satisfied against Progress. */
  earned: (p: Progress) => boolean
}

// ── Progress / mastery ──────────────────────────────────────────────────

export type Mastery = 'not-started' | 'introduced' | 'practicing' | 'competent' | 'mastered'

export interface LessonProgress {
  lessonId: string
  firstCompletedAt?: number
  lastCompletedAt?: number
  timesCompleted: number
  mastery: Mastery
  missedExerciseIds: string[]
}

export interface Progress {
  xp: number
  streakDays: number
  streakLastDay: string | null        // YYYY-MM-DD (local)
  dailyGoalXp: number
  lessons: Record<string, LessonProgress>
  earnedBadges: BadgeId[]
  completedScenarios: Record<string, number> // scenarioId -> timesCompleted
}

// ── Tutor channel ───────────────────────────────────────────────────────

export interface TutorTurn {
  id: string
  role: 'student' | 'tutor'
  text: string
  ts: number
  lessonId?: string
}

export interface TutorContext {
  activeLessonId?: string
  activeWorldId?: WorldId
  recentMistakeTags: string[]
}
